repositoryUrl: https://github.com/Dynamsoft/web-twain-docs/blob/master
firstLevelUrl: /web-twain/docs
repository: Dynamsoft/web-twain-docs
docFullPath: https://www.dynamsoft.com/web-twain/docs
productUrl: https://www.dynamsoft.com/Products/WebTWAIN_Overview.aspx
productName: Dynamic Web TWAIN
docHomePage: /web-twain/docs/
dynamsoft_logo: /web-twain/docs/assets/img-icon/dynamsoft-logo.png
dwt_logo: /web-twain/docs/assets/img-icon/dwt-logo.png
edit_icon: /web-twain/docs/assets/img-icon/edit-icon.png

assets: /web-twain/docs/assets/
_includes: /web-twain/docs/_includes/
_layouts: /web-twain/docs/_layouts/
about: /web-twain/docs/about/
getstarted: /web-twain/docs/getstarted/
indepth: /web-twain/docs/indepth/
info: /web-twain/docs/info/

dynamsoft_logo: /web-twain/docs/assets/img-icon/dynamsoft-logo.png
dbr_logo: /web-twain/docs/assets/img-icon/dbr-logo.png
edit_icon: /web-twain/docs/assets/img-icon/edit-icon.png
smile_icon: /web-twain/docs/assets/img-icon/icon-smile.png
sad_icon: /web-twain/docs/assets/img-icon/icon-sad.png
dbr_icon: /web-twain/docs/assets/img-icon/icon-dbr.svg
dwt_icon: /web-twain/docs/assets/img-icon/icon-dwt.svg
dnt_icon: /web-twain/docs/assets/img-icon/icon-dnt.svg

baseurl: /web-twain/docs/

theme: jekyll-theme-cayman
